# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: 모두를 위한 Physics-informed neural networks
author: Jaemin Oh
#logo: logo.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: auto

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - library.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/jaeminoh/PINNs # Online location of your book

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true

parse:
  myst_enable_extensions:
    # don't forget to list any other extensions you want enabled,
    # including those that are enabled by default!
    - amsmath
    - dollarmath

sphinx:
  extra_extensions:
    - sphinx_proof
  config:
    bibtex_reference_style: author_year